### ISSUE TITLE
(tooltip) Someone re-phrase cant end turn text 

### ISSUE THREAD

**Issue by gwodny** [EastsidePreparatorySchool/Krios-2019-Hunt-the-Wumpus#31]
rephrase:

> You have to do an action such as sending troops to battle to end your turn

**Comment by ghost** [comment]
Maybe disable the button and leave a tooltip saying "You must make a move on the Planet to end your turn"?

**Comment by gwodny** [comment]
hmmm interesting. I don't know how to do tooltips but that could work

**Comment by gwodny** [comment]
for the time being, I'll just replace the text with "You must make a move on the planet to end your turn" but I'll leave this issue open for more improvement i.e. making it a tooltip

**Comment by gwodny** [comment]
just realized my current implementation is flawed because it only works if "confirm end turn" is on. when I'm done working on the cursor I'll come back to this
