### ISSUE TITLE
Nuking when out of nukes still does animation and throws a null error for OutOfNukesText

### ISSUE THREAD

**Issue by gwodny** [EastsidePreparatorySchool/Krios-2019-Hunt-the-Wumpus#72]

**Comment by ghost** [comment]
Oof, I'll take a look

**Comment by gwodny** [comment]
now that I know how, we could disable it alltogether and have a tooltip like for end turn

**Comment by ghost** [comment]
I've already made a fix in my branch (not pushed yet) that will fix the ref error, but we should still have it linked to the tooltip. Maybe we can replace all of those larger heading-like texts with tooltips?

**Comment by gwodny** [comment]
yeah, all the "out of _____" ones, but other things like encountered bats should probably stay

**Comment by ghost** [comment]
oh yeah ofc 👍
