### ISSUE TITLE
coming back from minigame says "succesfully removed..." even when you lose or surrender

### ISSUE THREAD

**Issue by gwodny** [EastsidePreparatorySchool/Krios-2019-Hunt-the-Wumpus#73]

**Comment by ghost** [comment]
Proper dev procedure:
- Find bug
- Fix bug
- Push to master/production 
- feel good that you fixed stuff
- Tell people all of the awesome new stuff there is
- Forget about it
- Then have someone remind of of the buggy mess you left behind
